/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.anhquan.DoukiDbus1.Credential */

#define DOUKI_DBUS_TYPE_CREDENTIAL (douki_dbus_credential_get_type ())
#define DOUKI_DBUS_CREDENTIAL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DOUKI_DBUS_TYPE_CREDENTIAL, DoukiDbusCredential))
#define DOUKI_DBUS_IS_CREDENTIAL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DOUKI_DBUS_TYPE_CREDENTIAL))
#define DOUKI_DBUS_CREDENTIAL_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), DOUKI_DBUS_TYPE_CREDENTIAL, DoukiDbusCredentialIface))

struct _DoukiDbusCredential;
typedef struct _DoukiDbusCredential DoukiDbusCredential;
typedef struct _DoukiDbusCredentialIface DoukiDbusCredentialIface;

struct _DoukiDbusCredentialIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_generate_password) (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_name) (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_password) (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_name) (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_name);

};

GType douki_dbus_credential_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *douki_dbus_credential_interface_info (void);
guint douki_dbus_credential_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void douki_dbus_credential_complete_get_name (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation,
    const gchar *name);

void douki_dbus_credential_complete_set_name (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation,
    gboolean result);

void douki_dbus_credential_complete_get_password (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation,
    const gchar *password);

void douki_dbus_credential_complete_generate_password (
    DoukiDbusCredential *object,
    GDBusMethodInvocation *invocation,
    const gchar *password);



/* D-Bus method calls: */
void douki_dbus_credential_call_get_name (
    DoukiDbusCredential *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean douki_dbus_credential_call_get_name_finish (
    DoukiDbusCredential *proxy,
    gchar **out_name,
    GAsyncResult *res,
    GError **error);

gboolean douki_dbus_credential_call_get_name_sync (
    DoukiDbusCredential *proxy,
    gchar **out_name,
    GCancellable *cancellable,
    GError **error);

void douki_dbus_credential_call_set_name (
    DoukiDbusCredential *proxy,
    const gchar *arg_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean douki_dbus_credential_call_set_name_finish (
    DoukiDbusCredential *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean douki_dbus_credential_call_set_name_sync (
    DoukiDbusCredential *proxy,
    const gchar *arg_name,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);

void douki_dbus_credential_call_get_password (
    DoukiDbusCredential *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean douki_dbus_credential_call_get_password_finish (
    DoukiDbusCredential *proxy,
    gchar **out_password,
    GAsyncResult *res,
    GError **error);

gboolean douki_dbus_credential_call_get_password_sync (
    DoukiDbusCredential *proxy,
    gchar **out_password,
    GCancellable *cancellable,
    GError **error);

void douki_dbus_credential_call_generate_password (
    DoukiDbusCredential *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean douki_dbus_credential_call_generate_password_finish (
    DoukiDbusCredential *proxy,
    gchar **out_password,
    GAsyncResult *res,
    GError **error);

gboolean douki_dbus_credential_call_generate_password_sync (
    DoukiDbusCredential *proxy,
    gchar **out_password,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define DOUKI_DBUS_TYPE_CREDENTIAL_PROXY (douki_dbus_credential_proxy_get_type ())
#define DOUKI_DBUS_CREDENTIAL_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DOUKI_DBUS_TYPE_CREDENTIAL_PROXY, DoukiDbusCredentialProxy))
#define DOUKI_DBUS_CREDENTIAL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DOUKI_DBUS_TYPE_CREDENTIAL_PROXY, DoukiDbusCredentialProxyClass))
#define DOUKI_DBUS_CREDENTIAL_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DOUKI_DBUS_TYPE_CREDENTIAL_PROXY, DoukiDbusCredentialProxyClass))
#define DOUKI_DBUS_IS_CREDENTIAL_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DOUKI_DBUS_TYPE_CREDENTIAL_PROXY))
#define DOUKI_DBUS_IS_CREDENTIAL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DOUKI_DBUS_TYPE_CREDENTIAL_PROXY))

typedef struct _DoukiDbusCredentialProxy DoukiDbusCredentialProxy;
typedef struct _DoukiDbusCredentialProxyClass DoukiDbusCredentialProxyClass;
typedef struct _DoukiDbusCredentialProxyPrivate DoukiDbusCredentialProxyPrivate;

struct _DoukiDbusCredentialProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  DoukiDbusCredentialProxyPrivate *priv;
};

struct _DoukiDbusCredentialProxyClass
{
  GDBusProxyClass parent_class;
};

GType douki_dbus_credential_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DoukiDbusCredentialProxy, g_object_unref)
#endif

void douki_dbus_credential_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DoukiDbusCredential *douki_dbus_credential_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
DoukiDbusCredential *douki_dbus_credential_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void douki_dbus_credential_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DoukiDbusCredential *douki_dbus_credential_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
DoukiDbusCredential *douki_dbus_credential_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON (douki_dbus_credential_skeleton_get_type ())
#define DOUKI_DBUS_CREDENTIAL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON, DoukiDbusCredentialSkeleton))
#define DOUKI_DBUS_CREDENTIAL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON, DoukiDbusCredentialSkeletonClass))
#define DOUKI_DBUS_CREDENTIAL_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON, DoukiDbusCredentialSkeletonClass))
#define DOUKI_DBUS_IS_CREDENTIAL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON))
#define DOUKI_DBUS_IS_CREDENTIAL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DOUKI_DBUS_TYPE_CREDENTIAL_SKELETON))

typedef struct _DoukiDbusCredentialSkeleton DoukiDbusCredentialSkeleton;
typedef struct _DoukiDbusCredentialSkeletonClass DoukiDbusCredentialSkeletonClass;
typedef struct _DoukiDbusCredentialSkeletonPrivate DoukiDbusCredentialSkeletonPrivate;

struct _DoukiDbusCredentialSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  DoukiDbusCredentialSkeletonPrivate *priv;
};

struct _DoukiDbusCredentialSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType douki_dbus_credential_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DoukiDbusCredentialSkeleton, g_object_unref)
#endif

DoukiDbusCredential *douki_dbus_credential_skeleton_new (void);


G_END_DECLS
